accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]
      

my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
  path('', views.index, name='index'),
  path('new/', views.new, name='new'),
  path('delete/<int:task_id>', views.delete, name='delete'),
  path('edit/<int:task_id>', views.edit, name='edit'), 
  path('completed/<int:task_id>', views.completed, name='completed')
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Task(models.Model):
  task = models.CharField(max_length=100, null=False)
  completed = models.BooleanField(default=False)
  target = models.DateTimeField()
  author = models.ForeignKey(
      User,
      on_delete=models.CASCADE,
  )

  def __str__(self):
    return self.task

  def expired(self):
    return self.target >= timezone.now()

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm 


class LoginForm(AuthenticationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'
      field.widget.attrs['placeholder'] = field.label  


class SignUpForm(UserCreationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'
      field.widget.attrs['placeholder'] = field.label  

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

todo/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    task = forms.CharField(min_length=1, max_length=100, required=True)
    completed = forms.BooleanField(required=False)
    target = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        required=True,
      )


    class Meta:
        model = Task
        fields = ('task', 'completed', 'target')

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from .forms import LoginForm, SignUpForm
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy


class Login(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/login.html'


# class SignUp(CreateView):
#     form_class = SignUpForm
#     template_name = "accounts/signup.html" 
#     success_url = reverse_lazy('todo:index')

#     def form_valid(self, form):
#         user = form.save() # formの情報を保存
#         login(self.request, user) # 認証
#         self.object = user 
#         return HttpResponseRedirect(self.get_success_url()) # リダイレクト

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        print(form.errors)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('todo:index'))
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TaskForm
from .models import Task
from accounts.forms import LoginForm
from django.utils import timezone
import datetime
from django.contrib.auth.decorators import login_required

@login_required

def render_index(request, form=None):
  user = request.user
  now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M")
  utc_time = timezone.now()
  task_list = Task.objects.filter(completed='False', author_id=user.id).order_by('-target').reverse()
  completed_task = Task.objects.filter(completed='True', author_id=user.id).order_by('-target')
  context = {'task_list': task_list, 'completed_task': completed_task, 'now': now, 'utc_time': utc_time, 'form': form}
  return render(request, 'todo/index.html', context)


def index(request):
  return render_index(request)

def new(request):
  if request.method == 'POST':
    user = request.user
    form = TaskForm(data=request.POST)
    if form.is_valid():
      task = form.save(commit=False)
      task.author_id = user.id
      task.save()
      return HttpResponseRedirect(reverse('todo:index'))
    else:
      form.add_error(None, 'タスクが未入力です')
      return render_index(request, form)


def delete(request, task_id):
  task = get_object_or_404(Task, pk=task_id)
  task.delete()
  return HttpResponseRedirect(reverse('todo:index'))

def edit(request, task_id):
  task = get_object_or_404(Task, pk=task_id)
  if request.method == 'POST':
    form = TaskForm(data=request.POST)
    if form.is_valid():
      task.task=request.POST['task']
      task.target=request.POST['target']
      task.save()
      return HttpResponseRedirect(reverse('todo:index'))
    else:
      return render_index(request)
  else:
    return render_index(request)

def completed(request, task_id):
  now = timezone.now()
  task = get_object_or_404(Task, pk=task_id)
  if request.method == 'POST':
    if request.POST['completed'] == 'True':
      task.completed =request.POST['completed']
      task.target = now
      task.save()
      return HttpResponseRedirect(reverse('todo:index'))
    else:
      task.completed = request.POST['completed']
      task.save()
      return HttpResponseRedirect(reverse('todo:index'))
  else:
    return render_index(request)

templates/accounts/login.html
{% extends 'todo/base.html' %}

{% block content %}
<div class="form-signin" style="width: 350px; margin: 100px auto;">
  <div class="text-center mb-4">
    <div class="h3 mb-3 font-weight-normal">
      <b>todoアプリ</b>
    </div>
    <div class="login-box-body">
      <p class="mb-4"><b>ログイン画面</b></p>
      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <div class="col-xs-4" style="margin: auto;">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログイン</button>
          </div>
        </div>
      </form>
      <p style="margin: 10px 0  0;">会員登録はこちら</p>
      <a href="/signup">signup</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/signup.html
{% extends 'todo/base.html' %}

{% block content %}
<div class="form-signin" style="width: 350px; margin: 100px auto;">
  <div class="text-center mb-4">
    <div class="h3 mb-3 font-weight-normal">
      <b>todoアプリ</b>
    </div>
    <div class="login-box-body">
      <p class="mb-4"><b>サインアップ画面</b></p>
      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <div class="col-xs-4" style="margin: auto;">
            <button type="submit" class="btn btn-primary btn-block btn-flat">サインアップ</button>
          </div>
        </div>
      </form>
      <p style="margin: 10px 0  0;">アカウントをお持ちの方はこちら</p>
      <a href="/login">login</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/todo/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>todoapp201001</title>
  </head>
  <body>
   {% block header %}
   {% endblock header %}
   {% block content %}
   
   {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'todo/edit.js' %}"></script>
  </body>
</html>

templates/todo/header.html
<div class="jumbotron jumbotron-fluid" style="padding-bottom: 40px;">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#" style="font-size: 30px; margin: auto;">Todoアプリ</a>
    </nav>
    {% if user.is_authenticated %}
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link">ユーザ名：{{ user.get_username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">
        <i class="fa fa-fw fa-sign-out"></i>ログアウト</a>
      </li>
    </ul>
    {% endif %}
  </div>
</div>

templates/todo/index.html
{% extends 'todo/base.html' %}


{% block header %}
  {% include "todo/header.html" %}
{% endblock header %}
{% block content %}
<div class='container'>
  <div class="alert alert-info" style="width: 70%; margin: 20px auto; text-align: center;">
    <form action="{% url 'todo:new'  %}" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col">
          {% for error in form.non_field_errors %}
            <p style="font-size: 10px; margin: 0; color: red; position: absolute; top: -10px; left: 150px;">{{ error }}</p>
          {% endfor %}
          <label for="new_task">タスク内容</label><br>
          <input type="text" name="task" class="form-control" id="new_task" value='' placeholder="取り組むタスクを入力">
        </div>
        <div class="col">
          <label for="new_target">期限</label><br>
          <input type="datetime-local" class="form-control" name="target", id="new_target" value="{{now}}">
        </div>
      </div>
    <input type="submit" value="タスクを追加" class="btn btn-primary" style="margin-top: 20px;">
    </form>
  </div>
  <div class="row">
    <div class="col-md-8 order-md-1">
    {% for task in task_list %}
    {% if task.target >= utc_time %}
      <div class="alert alert-info" role="alert">
    {% else %}
      <div class="alert alert-warning" role="alert">
        <p style="color: red;"><strong>期限が切れています！！</strong></p>
    {% endif %}
        <div style="margin-bottom: 5px;">
          <form action="{% url 'todo:completed' task.pk %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="completed" value='True'>
            <input type="submit" value="" style="height: 5px; padding: 4px; float: left; margin: 6px;">
          </form>
          <p id="task_{{ task.id }}" style="display: inline;">{{ task.task }}</p>
          <p class="badge badge-danger" id="target_{{ task.id }}" value="{{ task.target|date:"Y-m-d H:i" }}"
           style="font-size: 15px; margin-left: 5px; display: inline;">期限：{{ task.target|date:"Y-m-j H:i" }}</p>
        </div>
        <form action="{% url 'todo:edit' task.pk %}" method="POST">
          {% csrf_token %}
          <div id="form_box_{{task.id}}" class="row"></div>
        </form>
        <a type="button" class="btn btn-primary" id="{{task.id}}" onclick="editFunction(this)" style="color: white;">編集</a>
        <form action="{% url 'todo:delete' task.pk %}" method="POST" class="btn">
          {% csrf_token %}
          <button type="submit" class="btn btn-success" aria-disabled="true" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
      </div>
    {% endfor %}
    </div> 
    <div class="col-md-4 order-md-2 mb-4">
      <p style="text-align: center;"><strong class="text-muted">完了済みのタスク</strong></p>
      {% for comp_task in completed_task %}
        <div class="alert alert-secondary" role="alert">
          <div style="margin-bottom: 5px;">
            <form action="{% url 'todo:completed' comp_task.pk %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="completed" value='False'>
              <input type="submit" value="" style="height: 5px; padding: 4px; float: left; margin: 6px;">
            </form>
            <p id="task_{{ task.id }}" style="display: inline;">{{ comp_task.task }}</p>
            <p class="badge badge-light" id="target_{{ task.id }}" style="font-size: 15px; margin-left: 5px; display: inline;">完了：{{ comp_task.target|date:"Y-m-j H:i" }}</p>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>


{% endblock content %}

todo/templates/todo/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>todoapp201001</title>
  </head>
  <body>
   {% block header %}
   {% endblock header %}
   {% block content %}
   
   {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/edit.js' %}"></script>
  </body>
</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block header %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#" style="font-size: 30px; margin: auto;">Todoアプリ</a>
    </nav>
  </div>
</div>
{% endblock header %}
{% block content %}
<div class='container'>
  <div class="alert alert-info" style="width: 70%; margin: 20px auto; text-align: center;">
    <form action="{% url 'new'  %}" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <label for="new_task">タスク内容</label><br>
          <input type="text" name="task" class="form-control" id="new_task" value='' placeholder="取り組むタスクを入力">
        </div>
        <div class="col">
          <label for="new_target">期限</label><br>
          <input type="datetime-local" class="form-control" name="target", id="new_target" value="{{now}}">
        </div>
      </div>
    <input type="submit" value="タスクを追加" class="btn btn-primary" style="margin-top: 5px;">
    </form>
  </div>
  <div class="row">
    <div class="col-md-8 order-md-1">
    {% for task in task_list %}
    {% if task.target >= utc_time %}
      <div class="alert alert-info" role="alert">
    {% else %}
      <div class="alert alert-warning" role="alert">
        <p style="color: red;"><strong>期限が切れています！！</strong></p>
    {% endif %}
        <div style="margin-bottom: 5px;">
          <form action="{% url 'completed' task.pk %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="completed" value='True'>
            <input type="submit" value="" style="height: 5px; padding: 4px; float: left; margin: 6px;">
          </form>
          <p id="task_{{ task.id }}" style="display: inline;">{{ task.task }}</p>
          <p class="badge badge-danger" id="target_{{ task.id }}" value="{{ task.target|date:"Y-m-d H:i" }}"
           style="font-size: 15px; margin-left: 5px; display: inline;">期限：{{ task.target|date:"Y-m-j H:i" }}</p>
        </div>
        <form action="{% url 'edit' task.pk %}" method="POST">
          {% csrf_token %}
          <div id="form_box_{{task.id}}" class="row"></div>
        </form>
        <a type="button" class="btn btn-primary" id="{{task.id}}" onclick="editFunction(this)" style="color: white;">編集</a>
        <form action="{% url 'delete' task.pk %}" method="POST" class="btn">
          {% csrf_token %}
          <button type="submit" class="btn btn-success" aria-disabled="true" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
      </div>
    {% endfor %}
    </div> 
    <div class="col-md-4 order-md-2 mb-4">
      <p style="text-align: center;"><strong class="text-muted">完了済みのタスク</strong></p>
      {% for comp_task in completed_task %}
        <div class="alert alert-secondary" role="alert">
          <div style="margin-bottom: 5px;">
            <form action="{% url 'completed' comp_task.pk %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="completed" value='False'>
              <input type="submit" value="" style="height: 5px; padding: 4px; float: left; margin: 6px;">
            </form>
            <p id="task_{{ task.id }}" style="display: inline;">{{ comp_task.task }}</p>
            <p class="badge badge-light" id="target_{{ task.id }}" style="font-size: 15px; margin-left: 5px; display: inline;">完了：{{ comp_task.target|date:"Y-m-j H:i" }}</p>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}